network:
    version: 2
    wifis:
        renderer: networkd
        wlan0:
            access-points:
                ARRIS-EB02-5G:
                    password: 427c867e8aaaa223d04b9e704de9c99ed313d609807ecbee6d70a136e386f686
            dhcp4: true
            optional: true

